const DISPOSABLE_DOMAINS = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "grr.la",
  "sharklasers.com",
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "10minutemail.com",
  "10minutemail.net",
  "minutemail.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "trashmail.com",
  "trashmail.me",
  "trashmail.net",
  "dispostable.com",
  "maildrop.cc",
  "getnada.com",
  "nada.email",
  "fakeinbox.com",
  "mintemail.com",
  "emailondeck.com",
  "throwaway.email",
  "mailnesia.com",
  "mailcatch.com",
  "mytemp.email",
  "tempail.com",
  "tempr.email",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "spamgourmet.com",
  "mailnull.com",
  "mailforspam.com",
  "spam4.me",
  "spambox.us",
  "spambox.xyz",
  "mail-temp.com",
  "tempinbox.com",
  "tempmailo.com",
  "tempmailaddress.com",
  "burnermail.io",
  "inboxkitten.com",
  "getairmail.com",
  "mohmal.com",
  "emailfake.com",
  "crazymailing.com",
  "mailpoof.com",
  "tmpmail.org",
  "tmpmail.net",
  "tmpmail.com",
  "fakemailgenerator.com",
  "emailtemporario.com.br",
  "mailtemp.net",
  "tempmail.ninja",
  "dropmail.me",
  "harakirimail.com",
  "mailinator.net",
  "mailinator2.com",
  "sogetthis.com",
  "spamherelots.com",
  "thisisnotmyrealemail.com",
  "mailmetrash.com",
  "trashymail.com",
  "jetable.org",
  "mailzilla.com",
  "mailzilla.org",
  "spamfree24.org",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "trbvm.com",
  "mailscrap.com",
  "mailtemp.info",
  "tempsky.com",
  "fakemail.net",
  "mailhazard.com",
  "mailhazard.us",
  "mailhz.me",
  "mailna.co",
  "mailna.in",
  "mailna.me",
  "meltmail.com",
  "mvrht.com",
  "nwldx.com",
  "pokemail.net",
  "spamspot.com",
  "tafmail.com",
  "tmail.ws",
  "tmailinator.com",
  "trash-mail.at",
  "trashmail.at",
  "trashmail.io",
  "trashmail.ws",
  "uggsrock.com",
  "veryrealemail.com",
  "zoemail.org",
]);

export function isDisposableEmailDomain(domain: string) {
  const normalized = domain.toLowerCase().trim();
  if (DISPOSABLE_DOMAINS.has(normalized)) {
    return true;
  }

  const parts = normalized.split(".");
  for (let i = 1; i < parts.length; i += 1) {
    const parent = parts.slice(i).join(".");
    if (DISPOSABLE_DOMAINS.has(parent)) {
      return true;
    }
  }

  return false;
}
